### ISSUE TITLE
Issue in setting up local enviornment and running it locally

### ISSUE THREAD

**Issue by umeshkarthik** [HHS/simpler-grants-pdf-builder#7]
We were trying to setup the application running locally
PS Y:\simpler-grants-pdf-builder\bloom_nofos> poetry run start
Getting the below   error

ModuleNotFoundError: No module named 'environ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Y:\simpler-grants-pdf-builder\bloom_nofos\manage.py", line 22, in <module>
    main()
  File "Y:\simpler-grants-pdf-builder\bloom_nofos\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\management\base.py", line 426, in run_from_argv
    connections.close_all()
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\utils\connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\utils\connection.py", line 76, in all
    return [
           ^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\utils\connection.py", line 73, in __iter__
    return iter(self.settings)
                ^^^^^^^^^^^^^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\utils\connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\utils\connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\conf\__init__.py", line 89, in __getattr__
    self._setup(name)
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\conf\__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ukrajeswaran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\conf\__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Y:\simpler-grants-pdf-builder\bloom_nofos\bloom_nofos\settings.py", line 16, in <module>
    import environ
    ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'environ'

**Comment by pcraig3** [comment]
Hello! Sorry about that, it must be that I have `environ` installed globally so I didn't notice that it wasn't in the `pyproject.toml` file. 

`environ` is used in the [`settings.py`](https://github.com/HHS/simpler-grants-pdf-builder/blob/main/bloom_nofos/bloom_nofos/settings.py#L16) file to import env vars. You should be able to use the default environment variables to get everything booted up in dev mode.

Let me know if you have any other problems!

**Comment by umeshkarthik** [comment]
Hi There,
I followed the exact same step as per the instruction below. Installed the
dhango-env still getting the error"No module named 'environ"
[image: image.png]

**Comment by pcraig3** [comment]
Okay, I'll do a clean install of this today and see if I can replicate this and fix it. Will update the issue when I do.

**Comment by umeshkarthik** [comment]
Hi Paul,
Thank you for your swift response. Also, do you know if this application is
publically hosted somewhere for testing purposes? If so can you please
share those information with us?

Thanks
Umesh K

**Comment by pcraig3** [comment]
Hi there! 

### first time setup 

I just ran through a clean install on my local environment and [updated the README](https://github.com/HHS/simpler-grants-pdf-builder/commit/fc3f2bf39c18a1caa41ec4c7cc5d3eddf91551cf) to make the first time setup clearer.

The main thing is that you need to copy the `.env.example` file to be a `.env` file in the bloom_nofos/bloom_nofos folder.

I also added the migration step that you'll need the first time the app is run.

### `environ` missing

I must admit I am confused about this one. Using poetry, you should be able to:

- clone the repo
- cd into the main folder 
- `poetry install`
- create .env file
- `cd bloom_nofos`
- `poetry run start`

You should also run the migrations but that's all I need to get the app booted up the first time. 

`import environ` in the settings actually refers to the [`django-environ`](https://pypi.org/project/django-environ/) package, and it was already in the poetry lockfile. Poetry should manage your virtualenv for you, so if you are using `poetry run start` or `poetry run python manage.py runserver`, the `django-environ` package should be in your virtualenv.

All I can say is that it worked for me on my Mac. It could be to do with you being on a Windows computer, but I didn't see anything on the github repo or on Google about Windows having a problem with `django-environ`.

### could I share the application

At this time, the NOFO Builder is an internal tool we are using as part of our work with the Health and Human Services department. If you are within the department, we would be happy to follow up about this, but otherwise I'm afraid I can't share the hosting information.

**Comment by umeshkarthik** [comment]
Hi Paul,
Thank you for your email. I work as a contractor for HRSA OP-Division. We
are trying to set it up on the Windows machine and we still have the same
issue after following your updated instructions. Please let us know if
there is any way we can get access to the hosted site.

Thanks
Umesh K

**Comment by apeterson-dmigs** [comment]
hi paul,
i have also been trying to run this service, and i got the server to successfully run. however, i am unsure if it is running in production mode or not. furthermore, if i want to create an account for this, there are no options on the site itself. this it what it looks like: 

![Screenshot 2024-05-16 152026](https://github.com/HHS/simpler-grants-pdf-builder/assets/170021418/9bf2534e-05f3-4cb7-9269-443f19c1891c)

in this photo, there is no option to let me sign up and add an account. what is the workaround for this issue?

**Comment by pcraig3** [comment]
Hi @apeterson-dmigs, 

Glad to see you got it running. Not addressing how users are created/managed was an oversight in the documentation.

I just pushed an update to the README that explains how to create a superuser account from the command line. ([Here's a Django tutorial that explains more about the superuser creation process](https://docs.djangoproject.com/en/5.0/intro/tutorial02/#creating-an-admin-user)). Once you have created a user account, you will be able to log in and add more accounts using the admin backend at localhost:8000/admin

The other thing you are likely to need is a NOFO template, unless you already have one. I am not sure how to proceed on this matter — I don't think I can provide one unless you send a formal request through an official channel.

**Comment by pcraig3** [comment]
Closing this issue as it is as resolved as it can be.

Going through the README instructions will get you set up to run the NOFO builder, but you will still need to import a Word Document to see it do anything interesting.

The NOFO Builder fully accepts `.docx` files now, although if you don't have a 'content guide' provided by our team, your mileage may vary. 

To be clear, we are running the NOFO Builder as a tool that we support our NOFO writers and coaches to use. We aren't supporting other instances at present. However, anyone is welcome to clone the repo and see how it works, etc.

If anyone in the thread would like any more help or explanation, please reach out to p.craig@bloomworks.digital or open a new issue.
